<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>

	<key>fileTypes</key>
	<array>
		<string>html</string>
		<string>htm</string>
		<string>tag</string>
	</array>
	<key>firstLineMatch</key>
	<string>\[.+?\]</string>
	<key>foldingStartMarker</key>
	<string>\[if[^\]]+\]</string>
	<key>foldingStopMarker</key>
	<string>\[\/if\]</string>
	<key>name</key>
	<string>Interchange</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?i)\[ *(perl).*interpolate=[^ \]0].*\]</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.ic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)(\[) */(\1) *(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.ic</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tmpl-container-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.perl</string>
				</dict>

			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)\[ *(calc) *\]</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.ic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)(\[) */(\1) *(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.ic</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tmpl-container-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.perl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>Documentation +&lt;&lt;EOD</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.ic</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>comment.block.ic</string>
			<key>end</key>
			<string>EOD</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.ic</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(\[ *(calcn|perl)\b.*\])|Routine +&lt;&lt;EOR</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.ic</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.perl</string>
			<key>end</key>
			<string>(?i)(\[) */(\2) *(\])|EOR</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.ic</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.perl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([A-Za-z]+) +&lt;&lt;([A-Z]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.ic</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.perl</string>
			<key>end</key>
			<string>^\2$</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.ic</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.perl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(\[ *(tmpn|set) *(\w+) *\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.character.ic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.ic</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.quoted.ic</string>
			<key>end</key>
			<string>(\[) */(\2) *(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.character.ic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ic</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(\[) *comment *(\])</string>
			<key>end</key> 
			<string>(?i)(\[) */comment *(\])</string>
			<key>name</key>
			<string>comment.block.ic</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(__|@@)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ic</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.ic</string>
			<key>end</key>
			<string>\1</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ic</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>@_</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ic</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.ic</string>
			<key>end</key>
			<string>_@</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ic</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#tmpl-container-tag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.ic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>entities</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.html</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
					<key>name</key>
					<string>constant.character.entity.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;</string>
					<key>name</key>
					<string>invalid.illegal.bad-ampersand.html</string>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ic</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.ic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tmpl-container-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>string-pipe-quoted</key>
		<dict>
			<key>begin</key>
			<string>\|</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\|</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ic</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.pipe.ic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tmpl-container-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ic</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.ic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tmpl-container-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>tmpl-container-tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\[/?)([A-Za-z\-_]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.ic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.ic</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key> 
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.character.ic</string>
						</dict>
					</dict>
					<key>name</key>
					<string>control.operator.ic</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#ic-stuff</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>ic-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(compare|object\.mv_results)\=(`|'|"|\|)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.ic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.ic</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.perl</string>
					<key>end</key>
					<string>\2</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.ic</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tmpl-container-tag</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.perl</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.perl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>control.operator.ic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.doublequoted.ic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([A-Za-z\-_0-9]+)(=)([^\s\]"'\|]+)</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Inline IC regex breaks page when containing quote characters.</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.ic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>control.operator.ic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.quoted.tt</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b([A-Za-z]+) +((?:=|\!)~) +((?:m|s|\/|y|tr|qr)[^\]]+)</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>This is a bad hack for things like the if scratch tag.</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.ic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.perl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(scratch|cgi|session|value|variable) +([0-9A-Za-z\-_\/\\]+)\b</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.ic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b([A-Za-z0-9_\-\\\/]+)\b</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.ic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\!\~|!|!=|=~|&gt;=|&gt;|&lt;|%|&lt;=|\*|\+|-|eq|ne|lt|lte|gt|gte|&amp;|&amp;&amp;|\|\|)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-pipe-quoted</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ic.tags</string>
	<key>uuid</key>
	<string>67D0DEC7-9E8C-44B3-8FA5-ADD9BBA05DE3</string>
</dict>
</plist>
