<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>

    <key>fileTypes</key>
    <array>
        <string>html</string>
        <string>htm</string>
        <string>tag</string>
    </array>
    <key>firstLineMatch</key>
    <string>\[.+?\]</string>
    <key>foldingStartMarker</key>
    <string>\[if\]</string>
    <key>foldingStopMarker</key>
    <string>\[\/if\]</string>
    <key>name</key>
    <string>Interchange</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>begin</key>
            <string>(\[/?)((?i:if|then|elsif|else|list|foreach|l|loc|tmp|tmpn|set|seti|errorbox|query|on-match|currency|time|strip|filter|fnet_button)\b)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>
                        punctuation.definition.tag.begin.ic
                        constant.character.ic
                    </string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.ic</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\]</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>
                        punctuation.definition.tag.end.ic
                        constant.character.ic
                    </string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.tag.block.any.ic</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-structure</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#ic-stuff</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>(\[)((?i:scratch|scratchd|value|area|template|include|data|userdb|setlocale|error)\b)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>
                        punctuation.definition.tag.begin.ic
                        constant.character.ic
                    </string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.inline.any.ic</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(\])</string>
            <key>endCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>
                        punctuation.definition.tag.end.ic
                        constant.character.ic
                    </string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.tag.inline.any.ic</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-structure</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#ic-stuff</string>
                </dict>
            </array>
        </dict>
        <!--
        <dict>
            <key>begin</key>
            <string>(?i)\[ *(perl).*interpolate=[^ ]+</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>comment.block.ic</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(?i)(\[) */(\1) *(\])</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>comment.block.ic</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-structure</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>source.perl</string>
                </dict>

            </array>
        </dict>
        -->
        <!--
        <dict>
            <key>begin</key>
            <string>(?i)\[ *(calc) *\]</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>comment.block.ic</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(?i)(\[) */(\1) *(\])</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>comment.block.ic</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-structure</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>source.perl</string>
                </dict>
            </array>
        </dict>
        -->
        <dict>
            <key>begin</key>
            <string>(?i)(\[*((?i:calcn|calc|condition|perl)\b).*? *\])|((\w*) *&lt;&lt;(EOR|EOF))</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>
                        punctuation.definition.tag.begin.ic
                    </string>
                </dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>
                        constant.character.ic
                    </string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>
                        entity.name.tag.ic
                        entity.name.function.ic
                    </string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>
                        constant.character.ic
                    </string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>
                        entity.name.tag.ic
                        punctuation.definition.tag.begin.ic
                    </string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>
                        entity.name.function.ic
                    </string>
                </dict>
            </dict>
            <key>contentName</key>
            <string>source.perl.embedded.ic</string>
            <key>end</key>
            <string>\[ */(\2) *\]|^(EOF|EOR)$</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>
                        punctuation.definition.tag.end.ic
                        constant.character.ic
                    </string>
                </dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>
                        punctuation.definition.tag.ic
                        entity.name.function.ic
                    </string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>
                        punctuation.definition.tag.ic
                        entity.name.function.ic
                    </string>
                </dict>

            </dict>
            <key>name</key>
            <string>
                source.perl.embedded.ic
                meta.tag.block.any.ic
            </string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-structure</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>source.perl</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>$self</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>(?i)(\[ *(tmp|tmpn|set|seti)\b *(\w+) *\])</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.ic punctuation.definition.tag.begin.ic</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.ic entity.name.tag.ic</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>support.function.ic</string>
                </dict>
            </dict>
            <key>contentName</key>
            <string>meta.tag.template.ic</string>
            <key>end</key>
            <string>(\[*/ *(\2) *\])</string>
            <key>endCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.ic</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.ic</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-structure</string>
                </dict>
            </array>

        </dict>
        <dict>
            <key>begin</key>
            <string>(__|@@)</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>variable.parameter.ic</string>
                </dict>
            </dict>
            <key>contentName</key>
            <string>variable.parameter.ic</string>
            <key>end</key>
            <string>\1</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>variable.parameter.ic</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>begin</key>
            <string>@_</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>variable.parameter.ic</string>
                </dict>
            </dict>
            <key>contentName</key>
            <string>variable.parameter.ic</string>
            <key>end</key>
            <string>_@</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>variable.parameter.ic</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>begin</key>
            <string>(?i)(\[ *(comment) *\])</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>
                        punctuation.definition.tag.begin.ic
                        constant.character.ic
                    </string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>
                        entity.name.tag.ic
                        comment.line.ic
                    </string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>
                        comment.block.ic
                    </string>
                </dict>
            </dict>
            <key>contentName</key>
            <string>comment.block.ic</string>
            <key>end</key> 
            <string>(?i)(\[ *(/comment) *\])</string>
            <key>endCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>
                        punctuation.definition.tag.end.ic
                        constant.character.ic
                    </string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>
                        entity.name.tag.ic
                        comment.line.ic
                    </string>
                </dict>
            </dict>
            <key>name</key>
            <string>
                comment.block.ic
                meta.tag.block.any.ic
            </string>
        </dict>
        <!-- Include patterns -->
        <dict>
            <key>include</key>
            <string>#tag-structure</string>
        </dict>
        <dict>
            <key>include</key>
            <string>text.html.ic</string>
        </dict>
    </array>


    <!-- ###################################################################
    ########################################################################
    ########   ____                      _ _                        ########
    ########  |  _ \ ___ _ __   ___  ___(_) |_ ___  _ __ _   _      ########
    ########  | |_) / _ \ '_ \ / _ \/ __| | __/ _ \| '__| | | |     ########
    ########  |  _ <  __/ |_) | (_) \__ \ | || (_) | |  | |_| |     ########
    ########  |_| \_\___| .__/ \___/|___/_|\__\___/|_|   \__, |     ########
    ########            |_|                              |___/      ########
    ########################################################################
    #################################################################### -->


    <key>repository</key>
    <dict>
        <key>entities</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.constant.html</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.constant.html</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
                    <key>name</key>
                    <string>constant.character.entity.html</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>&amp;</string>
                    <key>name</key>
                    <string>invalid.illegal.bad-ampersand.html</string>
                </dict>
            </array>
        </dict>
        <key>string-double-quoted</key>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.ic</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.ic</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.ic</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-structure</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#entities</string>
                </dict>
            </array>
        </dict>
        <key>string-single-quoted</key>
        <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.ic</string>
                </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.ic</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.ic</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-structure</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#entities</string>
                </dict>
            </array>
        </dict>
        <key>string-grave-quoted</key>
        <dict>
            <key>begin</key>
            <string>`</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.ic</string>
                </dict>
            </dict>
            <key>end</key>
            <string>`</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.ic</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.grave.ic</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#entities</string>
                </dict>
            </array>
        </dict>
        <key>string-pipe-quoted</key>
        <dict>
            <key>begin</key>
            <string>\|</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.ic</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\|</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.ic</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.pipe.ic</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-structure</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#entities</string>
                </dict>
            </array>
        </dict>

        <!--
        [06/17/2012] Attempt #1 at IC Tag Attribute Support
        <key>tag-generic-attribute</key>
        <dict>
            <key>captures</key>
            <dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.separator.key-value.tt</string>
                </dict>
            </dict>
            <key>match</key>
            ##Original## <string>\b([a-zA-Z-_:]+)\s*(=)</string>
            ##Attempt ## <string>\b(name|list|href|parse)\b\s*(=)</string>
            <key>name</key>
            <string>entity.other.attribute-name.tt</string>
        </dict>
        -->

        <key>tag-structure</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>(\[)(/?)([A-Za-z\-_]+) (\w+)?</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>constant.character.ic</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>constant.character.ic</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.control.ic</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>support.function.ic</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>\]</string>
                    <key>endCaptures</key> 
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>constant.character.ic</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>meta.tag.template.ic</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#ic-stuff</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>$self</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>

        <!-- ###########################################################
        ################################################################
        ####     __   ___ ____   __   ____  _          __  __       ####
        ####    | _| |_ _/ ___| |_ | / ___|| |_ _   _ / _|/ _|      ####
        ####    | |   | | |      | | \___ \| __| | | | |_| |_       ####
        ####    | |   | | |___   | |  ___) | |_| |_| |  _|  _|      ####
        ####    | |  |___\____|  | | |____/ \__|\__,_|_| |_|        ####
        ####    |__|            |__|                                ####
        ####                                                        ####
        ################################################################
        ############################################################ -->

        <key>ic-stuff</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>(compare)\=(`|'|"|\|)</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>support.function.ic</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>string.quoted.ic</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>source.perl.embedded.ic</string>
                    <key>end</key>
                    <string>\2</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>string.quoted.ic</string>
                        </dict>
                    </dict>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.perl</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>support.function.perl</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>control.operator.ic</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>string.doublequoted.ic</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>([A-Za-z\-_0-9]+)(=)([^\s\]"'\|]+)</string>
                </dict>
                <dict>
                    <key>comment</key>
                    <string>This is a bad hack for things like the if scratch tag.</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.control.ic</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>support.function.perl</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>\b(scratch|cgi|session|value|variable) +([0-9A-Za-z\-_\/\\]+)\b</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>variable.other.ic</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(\!\~|!|!=|=~|&gt;=|&gt;|&lt;|%|&lt;=|\*|\+|-|eq|ne|lt|lte|gt|gte|&amp;|&amp;&amp;|\|\|)</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>support.function.ic</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>\b([A-Za-z0-9_\-\\\/]+)\b</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#string-double-quoted</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#string-single-quoted</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#string-grave-quoted</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#string-pipe-quoted</string>
                </dict>
            </array>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>source.ic.tags</string>
    <key>uuid</key>
    <string>67D0DEC7-9E8C-44B3-8FA5-ADD9BBA05DE3</string>
</dict>
</plist>


<!--
ChangeLog:
    v1.1
    [05/24/12]
    - Added IC tag, FNET_BUTTON(:330)

    v1.2
    [06/13/12]
    - Grave/Backtick Quote (`) Support (:205-240)
        - Resolved: `... || []` string hangs open; 2nd grave doesn't close
    [08/08/12]
    - Added IC tags, STRIP|TMPN|CONDITION|DUMP|FLAG|ERRORBOX|QUERY
    [08/10/12]
    - Major Dev Collab w/ Nick; figured out broken #embedded-code repo/include
    [08/13/12]
    - Fixed/cleaned #embedded-code repo/include

    v2.1
    [08/27/12]
    - Rebase Nick's New v2.0 rebuild of .tmLanguage
    - v2.0 fixes:
        - apostrophe (') inside [L]
            - make it ok for only x1(') to exist
            - don't look for a matching (') inside tag
        - IC Tag attribute support (:250)
            - [08/09/12]: Assigned to Nick
        - $Scratch->{key_name}
            - > is not highlighted right
        - perl hash => key (really just '=>') support
          - see constant.other.key.perl (??? maybe)
          - fixed w/ more definitive embedded perl defs
    - v2.1 add:
        - grave-quote fix from v1.2
    [08/29/12]
    - v2.1 add
        - [perl] embedded-perl colors & definitions
    [09/07/12]
    - v2.1 add
        - Matching paired tags (pattern1)
        - Defined unpaired tags (pattern2)



ToDo:
    ^ match [if] with correpsonding [/if]
        - [tmp], [tmpn], [perl], [set], [conditon], [L], [foreach], [filter]
        - interpolate vs. non-interpolate
          - interpolate: calc, perl interpolate=<anything but 0>, seti, tmp
          - non-interpolate: calcn, perl, set, tmpn
          - ???: [L] [l] [loc]
    NEW:
    - lost HTML comment <!-- hotkey support
    - add [comment][/comment] keybind support
    - IC-tags to work inside attribute values ""
        - 05_view coupon_popup
    X [error_box] green (like perl|condition) but not embedded perl
    - format [perl|calcn|condition] stuff to revamped [comment]


Reject:
    - (?) support “ ” ’ (ASCII quote characters)
        - I use UTF-8; so no need

-->